<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IntunePackageBuilder.Generation</RootNamespace>
    <AssemblyName>IntunePackageBuilder.Generation</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IntunePackageBuilder.Core\IntunePackageBuilder.Core.csproj" />
  </ItemGroup>
</Project>
