# Behavior tests of the generated detection script (SPEC section 8.3, checks A15 and A16).
# The script is generated by the built Generation assembly and run in a child Windows PowerShell 5.1 process
# against real registry keys and real files. Runs under Windows PowerShell 5.1 and Pester 5.

BeforeAll {
    $repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
    $bin = Join-Path $repoRoot 'src\IntunePackageBuilder.Generation\bin\Release\net48'
    foreach ($name in 'Newtonsoft.Json', 'IntunePackageBuilder.Core', 'IntunePackageBuilder.Generation') {
        $dll = Join-Path $bin ($name + '.dll')
        if (-not (Test-Path -LiteralPath $dll)) {
            throw "Missing $dll. Build first: dotnet build src/IntunePackageBuilder.Generation -c Release"
        }
        Add-Type -Path $dll
    }

    $script:workDir = Join-Path ([System.IO.Path]::GetTempPath()) ('ipb-detect-' + [System.Guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $script:workDir | Out-Null
    $script:uninstallPath = 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall'

    function Invoke-Detection {
        param([string]$ScriptText)
        # The script is the only file in its folder and runs from another folder: it cannot rely on package files.
        $scriptDir = Join-Path $script:workDir ([System.Guid]::NewGuid().ToString('N'))
        $runDir = Join-Path $script:workDir ([System.Guid]::NewGuid().ToString('N'))
        New-Item -ItemType Directory -Path $scriptDir, $runDir | Out-Null
        $file = Join-Path $scriptDir 'Detect-App.ps1'
        [IntunePackageBuilder.Generation.Scripts.DetectionScriptGenerator]::WriteTo($file, $ScriptText)
        Push-Location $runDir
        try {
            $output = @(& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $file 2>$null)
            $exitCode = $LASTEXITCODE
        }
        finally {
            Pop-Location
        }
        [pscustomobject]@{ ExitCode = $exitCode; Output = ($output -join "`n").Trim() }
    }

    function New-MsiScript {
        param([string]$ProductCode, [string]$Minimum)
        [IntunePackageBuilder.Generation.Scripts.DetectionScriptGenerator]::GenerateForMsi('20261008-153412-a3f9', $ProductCode, $Minimum)
    }

    function New-FileScript {
        param([string]$Path, [string]$Minimum)
        [IntunePackageBuilder.Generation.Scripts.DetectionScriptGenerator]::GenerateForFile('20261008-153412-a3f9', $Path, $Minimum)
    }

    function Get-SampleScript {
        param([string]$Kind)
        if ($Kind -eq 'MSI') {
            New-MsiScript -ProductCode '{8F2C41A7-5B3E-4D19-A7C0-3E6D21B94F05}' -Minimum '4.2.1'
        }
        else {
            New-FileScript -Path 'C:\Program Files\Contoso''s App\app.exe' -Minimum '1.0'
        }
    }

    function Set-UninstallEntry {
        param([string]$ProductCode, [string]$DisplayVersion, [Microsoft.Win32.RegistryView]$View)
        $base = [Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, $View)
        try {
            $key = $base.CreateSubKey($script:uninstallPath + '\' + $ProductCode)
            try { $key.SetValue('DisplayVersion', $DisplayVersion) } finally { $key.Dispose() }
        }
        finally {
            $base.Dispose()
        }
    }

    function Remove-UninstallEntry {
        param([string]$ProductCode)
        foreach ($view in [Microsoft.Win32.RegistryView]::Registry64, [Microsoft.Win32.RegistryView]::Registry32) {
            $base = [Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, $view)
            try { $base.DeleteSubKeyTree($script:uninstallPath + '\' + $ProductCode, $false) } finally { $base.Dispose() }
        }
    }

    function Find-Ps7OnlySyntax {
        param([string]$Text)
        if ($Text -match '\?\?') { 'null-coalescing operator' }
        if ($Text -match '&&|\|\|') { 'pipeline chain operator' }
        if ($Text -match 'ForEach-Object\s+-Parallel') { 'ForEach-Object -Parallel' }
        if ($Text -match '\)\s*\?\s*[^\s]') { 'ternary operator' }
    }
}

AfterAll {
    Remove-Item -Recurse -Force $script:workDir -ErrorAction SilentlyContinue
}

Describe 'Generated detection script: form' {
    It 'parses without errors in Windows PowerShell 5.1 (<Kind>)' -ForEach @(
        @{ Kind = 'MSI' },
        @{ Kind = 'file' }
    ) {
        $text = Get-SampleScript -Kind $Kind
        $file = Join-Path $script:workDir 'parse.ps1'
        [IntunePackageBuilder.Generation.Scripts.DetectionScriptGenerator]::WriteTo($file, $text)
        $errors = $null
        $tokens = $null
        [void][System.Management.Automation.Language.Parser]::ParseFile($file, [ref]$tokens, [ref]$errors)
        @($errors) | Should -BeNullOrEmpty
        $bytes = [System.IO.File]::ReadAllBytes($file)
        ($bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) | Should -BeTrue
        @(Find-Ps7OnlySyntax -Text $text) | Should -BeNullOrEmpty
    }
}

Describe 'Generated MSI detection script (A15)' {
    BeforeEach {
        $script:code = '{' + [System.Guid]::NewGuid().ToString().ToUpperInvariant() + '}'
    }

    AfterEach {
        Remove-UninstallEntry -ProductCode $script:code
    }

    It 'does not detect software that is not installed' {
        $result = Invoke-Detection -ScriptText (New-MsiScript -ProductCode $script:code -Minimum '4.2.1')
        $result.ExitCode | Should -Be 1
        $result.Output | Should -BeNullOrEmpty
    }

    It 'rates installed version <Installed> against minimum <Minimum> as detected = <Detected>' -ForEach @(
        @{ Installed = '4.1.9'; Minimum = '4.2.1'; Detected = $false },
        @{ Installed = '4.2.0.99'; Minimum = '4.2.1'; Detected = $false },
        @{ Installed = '4.2.1'; Minimum = '4.2.1'; Detected = $true },
        @{ Installed = '4.2.1.0'; Minimum = '4.2.1'; Detected = $true },
        @{ Installed = '4.2.2'; Minimum = '4.2.1'; Detected = $true },
        @{ Installed = '5.0'; Minimum = '4.2.1'; Detected = $true },
        @{ Installed = '1.10'; Minimum = '1.9'; Detected = $true },
        @{ Installed = '1.9'; Minimum = '1.10'; Detected = $false },
        @{ Installed = '4.2.1-beta'; Minimum = '4.2.1'; Detected = $true },
        @{ Installed = 'v4.2.1'; Minimum = '4.2.1'; Detected = $true },
        @{ Installed = ''; Minimum = '4.2.1'; Detected = $false },
        @{ Installed = 'unknown'; Minimum = '4.2.1'; Detected = $false },
        @{ Installed = '4.2.1.7.9'; Minimum = '4.2.1'; Detected = $false }
    ) {
        Set-UninstallEntry -ProductCode $script:code -DisplayVersion $Installed -View ([Microsoft.Win32.RegistryView]::Registry64)
        $result = Invoke-Detection -ScriptText (New-MsiScript -ProductCode $script:code -Minimum $Minimum)
        if ($Detected) {
            $result.ExitCode | Should -Be 0
            $result.Output | Should -Not -BeNullOrEmpty
        }
        else {
            $result.ExitCode | Should -Be 1
            $result.Output | Should -BeNullOrEmpty
        }
    }

    It 'detects an installation in the 32-bit registry view' {
        Set-UninstallEntry -ProductCode $script:code -DisplayVersion '4.2.1' -View ([Microsoft.Win32.RegistryView]::Registry32)
        $result = Invoke-Detection -ScriptText (New-MsiScript -ProductCode $script:code -Minimum '4.2.1')
        $result.ExitCode | Should -Be 0
        $result.Output | Should -Match '4\.2\.1'
    }

    It 'does not detect a different product that is installed (foreign software)' {
        $other = '{' + [System.Guid]::NewGuid().ToString().ToUpperInvariant() + '}'
        try {
            Set-UninstallEntry -ProductCode $other -DisplayVersion '9.9.9' -View ([Microsoft.Win32.RegistryView]::Registry64)
            $result = Invoke-Detection -ScriptText (New-MsiScript -ProductCode $script:code -Minimum '4.2.1')
            $result.ExitCode | Should -Be 1
            $result.Output | Should -BeNullOrEmpty
        }
        finally {
            Remove-UninstallEntry -ProductCode $other
        }
    }

    It 'detects an installation that came from another distribution channel (nothing but the registration exists)' {
        Set-UninstallEntry -ProductCode $script:code -DisplayVersion '4.3.0' -View ([Microsoft.Win32.RegistryView]::Registry64)
        $result = Invoke-Detection -ScriptText (New-MsiScript -ProductCode $script:code -Minimum '4.2.1')
        $result.ExitCode | Should -Be 0
    }

    It 'is not detected any more once the registration is removed' {
        Set-UninstallEntry -ProductCode $script:code -DisplayVersion '4.2.1' -View ([Microsoft.Win32.RegistryView]::Registry64)
        (Invoke-Detection -ScriptText (New-MsiScript -ProductCode $script:code -Minimum '4.2.1')).ExitCode | Should -Be 0
        Remove-UninstallEntry -ProductCode $script:code
        (Invoke-Detection -ScriptText (New-MsiScript -ProductCode $script:code -Minimum '4.2.1')).ExitCode | Should -Be 1
    }
}

Describe 'Generated file detection script (A15)' {
    BeforeAll {
        $script:reference = Join-Path $env:SystemRoot 'System32\kernel32.dll'
        $info = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($script:reference)
        $script:exact = '{0}.{1}.{2}.{3}' -f $info.FileMajorPart, $info.FileMinorPart, $info.FileBuildPart, $info.FilePrivatePart
        $script:higher = '{0}.0.0.0' -f ($info.FileMajorPart + 1)
    }

    It 'has a reference file with version information' {
        $script:exact | Should -Not -Be '0.0.0.0'
    }

    It 'does not detect a file that is older than the minimum version' {
        $result = Invoke-Detection -ScriptText (New-FileScript -Path $script:reference -Minimum $script:higher)
        $result.ExitCode | Should -Be 1
        $result.Output | Should -BeNullOrEmpty
    }

    It 'detects a file with exactly the minimum version' {
        $result = Invoke-Detection -ScriptText (New-FileScript -Path $script:reference -Minimum $script:exact)
        $result.ExitCode | Should -Be 0
        $result.Output | Should -Not -BeNullOrEmpty
    }

    It 'detects a file that is newer than the minimum version' {
        $result = Invoke-Detection -ScriptText (New-FileScript -Path $script:reference -Minimum '1.0')
        $result.ExitCode | Should -Be 0
    }

    It 'resolves an environment variable in the path' {
        $result = Invoke-Detection -ScriptText (New-FileScript -Path '%SystemRoot%\System32\kernel32.dll' -Minimum '1.0')
        $result.ExitCode | Should -Be 0
    }

    It 'does not detect a missing file' {
        $result = Invoke-Detection -ScriptText (New-FileScript -Path (Join-Path $script:workDir 'missing.exe') -Minimum '1.0')
        $result.ExitCode | Should -Be 1
        $result.Output | Should -BeNullOrEmpty
    }

    It 'does not detect a path with an unknown environment variable' {
        $result = Invoke-Detection -ScriptText (New-FileScript -Path '%IPB_NO_SUCH_VARIABLE%\app.exe' -Minimum '1.0')
        $result.ExitCode | Should -Be 1
    }

    It 'does not detect a file without version information' {
        $plain = Join-Path $script:workDir 'plain.txt'
        Set-Content -LiteralPath $plain -Value 'no version' -Encoding ASCII
        $result = Invoke-Detection -ScriptText (New-FileScript -Path $plain -Minimum '0.0.1')
        $result.ExitCode | Should -Be 1
        $result.Output | Should -BeNullOrEmpty
    }

    It 'does not detect a directory with the configured name' {
        $dir = Join-Path $script:workDir 'folder.exe'
        New-Item -ItemType Directory -Path $dir | Out-Null
        (Invoke-Detection -ScriptText (New-FileScript -Path $dir -Minimum '1.0')).ExitCode | Should -Be 1
    }

    It 'treats a path with quotes and PowerShell syntax as plain text' {
        $marker = Join-Path $script:workDir 'injected.txt'
        $path = "C:\x'; Set-Content -LiteralPath '$marker' -Value x; '\a.exe"
        $result = Invoke-Detection -ScriptText (New-FileScript -Path $path -Minimum '1.0')
        $result.ExitCode | Should -Be 1
        Test-Path -LiteralPath $marker | Should -BeFalse
    }

    It 'handles a path with a typographic apostrophe and wildcard characters literally' {
        $dir = Join-Path $script:workDir ('it' + [char]0x2019 + 's [x]')
        New-Item -ItemType Directory -Path $dir | Out-Null
        Copy-Item -LiteralPath $script:reference -Destination (Join-Path $dir 'k.dll')
        $result = Invoke-Detection -ScriptText (New-FileScript -Path (Join-Path $dir 'k.dll') -Minimum '1.0')
        $result.ExitCode | Should -Be 0
    }
}

Describe 'Generated detection script without package or Intune cache (A16)' {
    It 'contains no reference to package files, the script folder or the Intune cache (<Kind>)' -ForEach @(
        @{ Kind = 'MSI' },
        @{ Kind = 'file' }
    ) {
        $text = Get-SampleScript -Kind $Kind
        $text | Should -Not -Match 'PSScriptRoot|PSCommandPath|MyInvocation|IntuneManagementExtension|Get-Location|Set-Location'
        $text | Should -Not -Match 'Set-Content|Out-File|New-Item|Add-Content|Remove-Item'
    }

    It 'runs from an empty folder without any package content and detects the installed state' {
        $code = '{' + [System.Guid]::NewGuid().ToString().ToUpperInvariant() + '}'
        try {
            Set-UninstallEntry -ProductCode $code -DisplayVersion '2.0.0' -View ([Microsoft.Win32.RegistryView]::Registry64)
            $result = Invoke-Detection -ScriptText (New-MsiScript -ProductCode $code -Minimum '2.0.0')
            $result.ExitCode | Should -Be 0
            $result.Output | Should -Not -BeNullOrEmpty
        }
        finally {
            Remove-UninstallEntry -ProductCode $code
        }
    }
}
