<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IntunePackageBuilder.Core</RootNamespace>
    <AssemblyName>IntunePackageBuilder.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="IntunePackageBuilder.Core.Tests" />
  </ItemGroup>
</Project>
