<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IntunePackageBuilder.Analysis</RootNamespace>
    <AssemblyName>IntunePackageBuilder.Analysis</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IntunePackageBuilder.Core\IntunePackageBuilder.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="IntunePackageBuilder.Analysis.Tests" />
  </ItemGroup>
</Project>
